disabled_rules:
- trailing_whitespace
- orphaned_doc_comment
- closure_parameter_position
- multiple_closures_with_trailing_closure
- unused_setter_value
- cyclomatic_complexity

identifier_name:
  excluded:
    - vc
    - i
    - id
    - x
    - y
    - I
    - ok

excluded: 
# paths to ignore during linting. Takes precedence over `included`.
- build
- docs
- Playground
- fastlane
- Frameworks
- Pods
- Announcer/Libraries
